# Generated by Django 4.2.7 on 2026-03-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('aadhar', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('VJNT', 'VJNT'), ('SBC', 'SBC'), ('NT-A', 'NT-A'), ('NT-B', 'NT-B'), ('NT-C', 'NT-C'), ('EWS', 'EWS'), ('DT', 'DT'), ('Other', 'Other')], default='General', max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('school', models.CharField(blank=True, choices=[('School of Chemical Sciences', 'School of Chemical Sciences'), ('School of Commerce and Management Sciences', 'School of Commerce and Management Sciences'), ('School of Computational Sciences', 'School of Computational Sciences'), ('School of Earth Sciences', 'School of Earth Sciences'), ('School of Educational Sciences', 'School of Educational Sciences'), ('School of Fine and Performing Arts', 'School of Fine and Performing Arts'), ('School of Language, Literature and Culture Studies', 'School of Language, Literature and Culture Studies'), ('School of Life Sciences', 'School of Life Sciences'), ('School of Mathematical Sciences', 'School of Mathematical Sciences'), ('School of Media Studies', 'School of Media Studies'), ('School of Pharmacy', 'School of Pharmacy'), ('School of Physical Sciences', 'School of Physical Sciences'), ('School of Social Sciences', 'School of Social Sciences'), ('School of Law', 'School of Law'), ('School of Technology', 'School of Technology')], max_length=200)),
                ('level', models.CharField(choices=[('UG', 'UG (Undergraduate)'), ('PG', 'PG (Postgraduate)')], default='UG', max_length=5)),
                ('course', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('hostel', models.CharField(choices=[('Boys Hostel 1', 'Boys Hostel 1'), ('Boys Hostel 2', 'Boys Hostel 2'), ('Boys Hostel 3', 'Boys Hostel 3'), ('Boys Hostel 4', 'Boys Hostel 4')], max_length=50)),
                ('room', models.CharField(blank=True, max_length=20)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('fees', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Pending', max_length=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_paid_date', models.DateField(blank=True, null=True)),
                ('marks_10', models.CharField(blank=True, max_length=5)),
                ('marks_12', models.CharField(blank=True, max_length=5)),
                ('marks_ug', models.CharField(blank=True, max_length=5)),
                ('marks_pg', models.CharField(blank=True, max_length=5)),
                ('biometric_id', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('destination', models.CharField(blank=True, max_length=300)),
                ('contact_during_leave', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('room', models.CharField(blank=True, max_length=20)),
                ('hostel', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('complaint_type', models.CharField(choices=[('Property Damage', 'Property Damage'), ('Maintenance', 'Maintenance'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Other', 'Other')], default='Property Damage', max_length=30)),
                ('description', models.TextField()),
                ('damage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damage_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('marksheet_10', '10th Marksheet'), ('marksheet_12', '12th Marksheet'), ('ug_marksheet', 'UG Marksheet'), ('income_certificate', 'Income Certificate'), ('caste_certificate', 'Caste Certificate'), ('aadhar_card', 'Aadhaar Card'), ('domicile_certificate', 'Domicile Certificate'), ('nationality_certificate', 'Nationality Certificate')], max_length=30)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='submitted', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hostel.student')),
            ],
            options={
                'ordering': ['doc_type'],
                'unique_together': {('student', 'doc_type')},
            },
        ),
    ]
