# Generated by Django 4.2.7 on 2026-03-28 13:46

from django.db import migrations, models
import hostel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_student_admission_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='contact_during_leave',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True, validators=[hostel.models.validate_aadhar]),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, validators=[hostel.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks_10',
            field=models.CharField(blank=True, max_length=6, validators=[hostel.models.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks_12',
            field=models.CharField(blank=True, max_length=6, validators=[hostel.models.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks_pg',
            field=models.CharField(blank=True, max_length=6, validators=[hostel.models.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks_ug',
            field=models.CharField(blank=True, max_length=6, validators=[hostel.models.validate_marks]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, validators=[hostel.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, validators=[hostel.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10, validators=[hostel.models.validate_phone]),
        ),
    ]
